apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: krkn-operator-console
  labels:
    app: krkn-operator-console
    app.kubernetes.io/name: krkn-operator-console
    app.kubernetes.io/component: web-console
    app.kubernetes.io/part-of: krkn-operator
spec:
  to:
    kind: Service
    name: krkn-operator-console
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
