apiVersion: v1
kind: Service
metadata:
  name: krkn-operator-console
  labels:
    app: krkn-operator-console
    app.kubernetes.io/name: krkn-operator-console
    app.kubernetes.io/component: web-console
    app.kubernetes.io/part-of: krkn-operator
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: krkn-operator-console
